version: '3.11'
services:
  web:
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    image: ticket_app:v1
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && sh /app/entrypoint.sh"

  postgres_db:
    image: postgres
    restart: always
    command: -p 5434
    env_file:
      - .env
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: